name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      - name: Check for any formatting issues
        run: flutter format --set-exit-if-changed .
      - name: Statically analyze
        run: flutter analyze .
      - name: Run tests
        run: flutter test
      - name: Generate build
        run: flutter build apk
      - name: Upload generated apk
        uses: actions/upload-artifact@master
